Repository Licruit/Licruit-frontend, pull requests merged in 2024-07, with the labels that each got.

#9 [Chore/#4]:sentry 설정
  .gitignore
  package-lock.json
  package.json
  src/main.tsx
Labels: chore

#11 [Feat/#10]: 비밀번호 찾기 유효성 검사 추가 & 폼 관련 코드 개선
  .eslintrc.cjs
  public/assets/icons/check.svg
  src/components/Header/Header.tsx
  src/constants/step.ts
  src/features/Auth/components/FindPassword/AuthWithIdForm.tsx
  src/features/Auth/components/FindPassword/FindPasswordForm.tsx
  src/features/Auth/components/Login/LoginForm.tsx
  src/features/Auth/components/common/Form/AuthForm.tsx
  src/features/Auth/components/common/Form/GenericForm.tsx
  src/features/Auth/components/common/Form/PasswordForm.tsx
  src/features/Auth/components/common/Form/PasswordInput.tsx
  src/features/Auth/components/common/FormTitle/FormTitle.tsx
  src/features/Auth/components/common/FormTitle/TitleAndStep.tsx
  src/features/Auth/components/common/PasswordForm.tsx
  src/features/Auth/constants/form.ts
  src/features/Auth/constants/formTitle.ts
  src/features/Auth/hooks/useFunnel.tsx
  src/features/Auth/index.ts
  src/pages/FindPasswordPage.tsx
  src/pages/LoginPage.tsx
Labels: feat, refactor

#12 [Chore/#8]: Vitest 세팅, CI yml 파일 생성
  .eslintignore
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/pages/CatelogDetailPage.tsx
  src/test/first.test.tsx
  vite.config.ts
Labels: chore

#17 [API/#7]: 로그인, 비밀번호 찾기 API 연동
  .eslintrc.cjs
  package-lock.json
  public/assets/icons/shoppingbag.svg
  src/api/http.ts
  src/components/Button/Button.tsx
  src/components/Header/Header.tsx
  src/components/Header/Navigation.tsx
  src/features/Auth/api/auth.api.ts
  src/features/Auth/api/findPassword.api.ts
  src/features/Auth/api/login.api.ts
  src/features/Auth/components/FindPassword/AuthWithIdForm.tsx
  src/features/Auth/components/Join/PasswordWithIdForm.tsx
  src/features/Auth/components/Login/LoginForm.tsx
  src/features/Auth/components/common/Form/AuthForm.tsx
  src/features/Auth/components/common/Form/GenericForm.tsx
  src/features/Auth/components/common/Timer.tsx
  src/features/Auth/constants/form.ts
  src/features/Auth/constants/timer.ts
  src/features/Auth/hooks/useCode.ts
  src/features/Auth/hooks/useLogin.ts
  src/features/Auth/index.ts
  src/features/Auth/types/login.d.ts
  src/features/Auth/types/signup.d.ts
  src/main.tsx
  src/pages/FindPasswordPage.tsx
  src/pages/LoginPage.tsx
  src/routes/PublicRoutes.tsx
  src/routes/index.tsx
  src/store/sessionStore.ts
Labels: API

#15 [Chore/#14]: ci yml 업데이트
  .github/workflows/ci.yml
Labels: chore
